on: [push]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: legoktm/gh-action-build-deb@debian-bullseye
        id: build-debian-bullseye
        with:
          args: -us -uc
        
      - uses: actions/upload-artifact@v2.2.4
        with:	
            name: fonts-as
            path: output
            
  download-artifcat:
    needs: build-deb
    runs-on: Workstation1
    steps:      
      - uses: actions/download-artifact@v2
        with:
          name: fonts-as

